const file = {
  playerName: "",
  characterName: "",
  level: "",
  raceAndClass: "",
  age: "",
  alignment: "",
  size: "",
  weight: "",
  height: "",
  combat: "",
  social: "",
  exploration: "",
  magic: "",
  athletics: "",
  fortitude: "",
  influence: "",
  knowledge: "",
  perception: "",
  stealth: "",
  health: "",
  stamina: "",
  will: "",
  mana: "",
  wealth: "",
  backgroundFeat: {
    name: "",
    value: "",
  },
  level1Feat: {
    name: "",
    value: "",
  },
  level2Feat: {
    name: "",
    value: "",
  },
  level3Feat: {
    name: "",
    value: "",
  },
  level4Feat: {
    name: "",
    value: "",
  },
  level5Feat: {
    name: "",
    value: "",
  },
  level6Feat: {
    name: "",
    value: "",
  },
  attunement1Feat: {
    name: "",
    value: "",
  },
  attunement2Feat: {
    name: "",
    value: "",
  },
  attunement3Feat: {
    name: "",
    value: "",
  },
  equipment: "",
  proficiencies: "",
  racePerks: "",
  reputation: "",
  movement: "",
  speed: "",
  jumping: "",
  vision: "",
  visionDistance: "",
  range: "",
  eyes: "",
  hair: "",
  skin: "",
  carryCapacity: "",
  maxMarchSpeed: "",
  maxMarchDistance: "",
  principles: "",
  flaws: "",
  description: "",
  backstory: "",
}

export default file