const file = {
  playerName: null,
  characterName: null,
  level: null,
  class: null,
  race: null,
  age: null,
  alignment: null,
  size: null,
  weight: null,
  height: null,
  combat: null,
  social: null,
  exploration: null,
  magic: null,
  athletics: null,
  fortitude: null,
  influence: null,
  knowledge: null,
  perception: null,
  stealth: null,
  health: null,
  stamina: null,
  will: null,
  mana: null,
  wealth: null,
  feats: {
    background: {
      name: null,
      value: null,
    },
    level1: {
      name: null,
      value: null,
    },
    level2: {
      name: null,
      value: null,
    },
    level3: {
      name: null,
      value: null,
    },
    level4: {
      name: null,
      value: null,
    },
    level5: {
      name: null,
      value: null,
    },
    level6: {
      name: null,
      value: null,
    },
    attunement1: {
      name: null,
      value: null,
    },
    attunement2: {
      name: null,
      value: null,
    },
    attunement3: {
      name: null,
      value: null,
    },
  },
  equipment: [],
  proficiencies: "",
  racePerks: "",
  reputation: "",
  movement: "",
  speed: "",
  jumping: "",
  vision: "",
  visionDistance: "",
  range: "",
  eyes: "",
  hair: "",
  skin: "",
  carryCapacity: "",
  maxMarchSpeed: "",
  maxMarchDistance: "",
  principles: "",
  flaws: "",
  description: "",
  backstory: "",
}

export default file