const file = {
  playerName: 'Joseph Reed',
  characterName: 'King Richard',
  level: '6',
  raceAndClass: 'Human Fighter',
  age: '35',
  alignment: 'Neutral',
  size: 'Medium',
  weight: '265 lbs',
  height: '6ft 3in',
  combat: '0',
  social: '1',
  exploration: '5',
  magic: '6',
  athletics: '0',
  fortitude: '1',
  influence: '2',
  knowledge: '4',
  perception: '5',
  stealth: '6',
  health: '5',
  stamina: '10',
  will: '15',
  mana: '20',
  wealth: '25',
  backgroundFeat: {
    name: 'World Renown',
    value: 'You are known in all the lands and are treated as such. Your reputation score is set to 5 honor or infamy in any land where royalty is respected.',
  },
  level1Feat: {
    name: 'Cultured',
    value: 'You have a current knowledge of the cultures and celebrities in any regions and any peculiar laws from those regions.'
  },
  level2Feat: {
    name: 'Politician',
    value: 'Gain 2 proficiency dice in Influence. You can spend one day in to learn their likes and dislikes of any politician.',
  },
  level3Feat: {
    name: 'Defensive Aura',
    value: 'You and any allies within 15 feet cannot be critically struck.',
  },
  level4Feat: {
    name: 'Signature Spell',
    value: 'Inspiring Presence',
  },
  level5Feat: {
    name: 'Battle Master',
    value: 'You are proficient in all weapons, armors, shields, and physical damage types. As part of a Free Action you can determine one combatants health, stamina, will, and mana.',
  },
  level6Feat: {
    name: 'Domain: Army',
    value: 'Enemies have vulnerability(1) to any damage type you are proficient with if there are at least 100 people within a 120ft radius who will fight for you.',
  },
  attunement1Feat: {
    value: 'Once per long rest give the effects of three short rests to any allies within your sight',
    name: 'Divine Recovery',
  },
  attunement2Feat: {
    name: '',
    value: '',
  },
  attunement3Feat: {
    name: '',
    value: '',
  },
  equipment: "equipment",
  proficiencies: "Slashing Damage\nCombat Proficiency Die (2)",
  racePerks: "Social Proficiency Die (2)",
  reputation: "reputation",
  movement: "Base",
  speed: "30",
  jumping: "1\n1\n10\n1\n1",
  vision: "Light",
  visionDistance: "Infinite / 60ft",
  range: "1\n1\n1\n1\n1",
  eyes: "blue",
  hair: "black",
  skin: "tanned",
  carryCapacity: "1",
  maxMarchSpeed: "1",
  maxMarchDistance: "1",
  principles: "principles",
  flaws: "flaws",
  description: "description",
  backstory: "backstory",
}

export default file