
export default {
  playerName: 'Joseph Reed',
  characterName: 'King Richard',
  level: '6',
  class: 'Fighter',
  race: 'Human',
  age: '35',
  alignment: 'Neutral',
  size: 'Medium',
  weight: '265 lbs',
  height: '6ft 3in',
  pillars: {
    combat: '1',
    social: '1',
    exploration: '1',
    magic: '1',
  },
  resources: {
    health: '1',
    stamina: '1',
    will: '1',
    mana: '1',
    wealth: '1',
  },
  feats: {
    background: 'background',
    level1: 'level1',
    level2: 'level2',
    level3: 'level3',
    level4: 'level4',
    level5: 'level5',
    level6: 'level6',
    attunement1: 'attunement1',
    attunement2: 'attunement2',
    attunement3: 'attunement3',
  },
  equipment: [],
  proficiencies: [],
  movement: [],
  jumping: {
    standingHigh: '1',
    standingLong: '1',
    runningStart: '1',
    runningHigh: '1',
    runningLong: '1',
  },
  vision: [],
  range: {
    accurateRange: '1',
    throwingBase: '1',
    throwingPenalty1: '1',
    throwingPenalty2: '1',
    throwingPenalty3: '1',
  }
}